# Generated by Django 4.2.21 on 2025-05-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the department', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the employee', max_length=255)),
                ('email', models.EmailField(help_text='Corporate or personal email address', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('address', models.TextField(help_text='Residential or mailing address')),
                ('date_of_joining', models.DateField(help_text='Date when the employee joined the organization')),
                ('department', models.ForeignKey(help_text='Department to which the employee belongs', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.department')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Performance rating on a scale from 1 to 5')),
                ('review_date', models.DateField(help_text='Date when the performance review was conducted')),
                ('employee', models.ForeignKey(help_text='Employee under review', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='employees.employee')),
            ],
        ),
    ]
