# Generated by Django 4.2.21 on 2025-05-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number', max_length=50),
        ),
    ]
