# Generated by Django 4.2.21 on 2025-05-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the attendance entry')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late')], help_text='Attendance status: Present, Absent, or Late', max_length=1)),
                ('employee', models.ForeignKey(help_text='Employee associated with this attendance record', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Attendance records',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
